import { Route,Routes } from 'react-router-dom'
import { DashboardPage } from '../pages/DashboardPage'
import { NotFoundPage } from '../pages/NotFoundPage'
import { ProfilePage } from '../pages/ProfilePage'
import { PreferencesPage } from '../pages/PreferencesPage'
import { ReusableAnswersPage } from '../pages/ReusableAnswersPage'
import { ResumeDocumentsPage } from '../pages/ResumeDocumentsPage'
import { ProfileVersionsPage } from '../pages/ProfileVersionsPage'
import { JobSourcesPage } from '../pages/JobSourcesPage'
import { JobSourceDetailPage } from '../pages/JobSourceDetailPage'
import { JobSourceRunsPage } from '../pages/JobSourceRunsPage'
import { JobsPage } from '../pages/JobsPage'
import { NewJobPage } from '../pages/NewJobPage'
import { JobDetailPage } from '../pages/JobDetailPage'
import { ApplicationPackagesPage } from '../pages/ApplicationPackagesPage'
import { ApplicationPackageDetailPage } from '../pages/ApplicationPackageDetailPage'
import { ApplicationPackageRevisionPage } from '../pages/ApplicationPackageRevisionPage'
import { ApplicationReviewPage } from '../pages/ApplicationReviewPage'
import { ApplicationReviewDetailPage } from '../pages/ApplicationReviewDetailPage'
import { ApplicationHandoffsPage } from '../pages/ApplicationHandoffsPage'
import { ApplicationHandoffPage } from '../pages/ApplicationHandoffPage'
import{MatchingSettingsPage}from'../pages/MatchingSettingsPage';import{EvaluationsPage}from'../pages/EvaluationsPage';import{EvaluationRunsPage}from'../pages/EvaluationRunsPage';import{EvaluationQualityPage}from'../pages/EvaluationQualityPage'
export function AppRoutes(){return <Routes><Route path="/" element={<DashboardPage/>}/><Route path="/profile" element={<ProfilePage/>}/><Route path="/preferences" element={<PreferencesPage/>}/><Route path="/reusable-answers" element={<ReusableAnswersPage/>}/><Route path="/resume-documents" element={<ResumeDocumentsPage/>}/><Route path="/profile/versions" element={<ProfileVersionsPage/>}/><Route path="/job-sources" element={<JobSourcesPage/>}/><Route path="/job-sources/:sourceId" element={<JobSourceDetailPage/>}/><Route path="/job-source-runs" element={<JobSourceRunsPage/>}/><Route path="/jobs" element={<JobsPage/>}/><Route path="/jobs/new" element={<NewJobPage/>}/><Route path="/jobs/:jobId" element={<JobDetailPage/>}/><Route path="/matching/settings" element={<MatchingSettingsPage/>}/><Route path="/evaluations" element={<EvaluationsPage/>}/><Route path="/evaluation-runs" element={<EvaluationRunsPage/>}/><Route path="/evaluation-quality" element={<EvaluationQualityPage/>}/><Route path="/application-review" element={<ApplicationReviewPage/>}/><Route path="/application-handoffs" element={<ApplicationHandoffsPage/>}/><Route path="/application-handoffs/:id" element={<ApplicationHandoffPage/>}/><Route path="/application-packages" element={<ApplicationPackagesPage/>}/><Route path="/application-packages/:packageId" element={<ApplicationPackageDetailPage/>}/><Route path="/application-packages/:packageId/revisions/:revisionId/review" element={<ApplicationReviewDetailPage/>}/><Route path="/application-packages/:packageId/revisions/:revisionId" element={<ApplicationPackageRevisionPage/>}/><Route path="*" element={<NotFoundPage/>}/></Routes>}
