package com.amit.jobagent.matching;
import com.amit.jobagent.audit.*;import com.amit.jobagent.job.*;import com.amit.jobagent.profile.version.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.*;import java.time.*;import java.util.*;import java.util.regex.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class DeterministicRuleService{
 private final JobRuleEvaluationRepository repo;private final ObjectMapper mapper;private final AuditService audit;
 public DeterministicRuleService(JobRuleEvaluationRepository r,ObjectMapper m,AuditService a){repo=r;mapper=m;audit=a;}
 @Transactional public RuleEvaluationResponse evaluate(JobMatchingView j,PublishedProfileSnapshot p,String ruleset){var cached=repo.findByJobIdAndProfileVersionIdAndRulesetVersionAndJobContentHashAndProfileSnapshotChecksum(j.id(),p.id(),ruleset,j.contentHash(),p.checksum());if(cached.isPresent())return map(cached.get(),true);var reasons=new ArrayList<RuleReasonCode>();var evidence=new LinkedHashMap<String,String>();status(j,reasons);var pref=p.snapshot().path("preferences");matchTerms(j.company(),pref.path("excludedCompanies"),RuleReasonCode.COMPANY_EXCLUDED,"company",reasons,evidence);matchTerms(j.location(),pref.path("excludedLocations"),RuleReasonCode.LOCATION_EXCLUDED,"location",reasons,evidence);String searchable=(j.title()+" "+Objects.toString(j.description(),"")).trim();matchTerms(searchable,pref.path("excludedKeywords"),RuleReasonCode.KEYWORD_EXCLUDED,"keyword",reasons,evidence);if(j.workplaceType()==WorkplaceType.REMOTE&&!pref.path("remoteAllowed").asBoolean())reasons.add(RuleReasonCode.WORKPLACE_TYPE_NOT_ALLOWED);if(j.workplaceType()==WorkplaceType.HYBRID&&!pref.path("hybridAllowed").asBoolean())reasons.add(RuleReasonCode.WORKPLACE_TYPE_NOT_ALLOWED);if(j.workplaceType()==WorkplaceType.ONSITE&&!pref.path("onsiteAllowed").asBoolean())reasons.add(RuleReasonCode.WORKPLACE_TYPE_NOT_ALLOWED);if(j.workplaceType()==WorkplaceType.UNSPECIFIED||j.location()==null||j.description()==null||j.description().isBlank())reasons.add(RuleReasonCode.INSUFFICIENT_JOB_DATA);boolean hard=reasons.stream().anyMatch(x->x!=RuleReasonCode.INSUFFICIENT_JOB_DATA);RuleResult result=hard?RuleResult.FAIL:reasons.isEmpty()?RuleResult.PASS:RuleResult.MANUAL_REVIEW;try{var saved=repo.saveAndFlush(new JobRuleEvaluation(j.id(),p.id(),ruleset,result,mapper.writeValueAsString(reasons),mapper.writeValueAsString(evidence),j.contentHash(),p.checksum()));audit.record(AuditEventType.RULE_EVALUATION_COMPLETED,"JobRuleEvaluation",saved.id,"{\"result\":\""+result+"\"}");return map(saved,false);}catch(Exception e){throw new IllegalStateException("Could not persist deterministic rule result",e);}}
 private static void status(JobMatchingView j,List<RuleReasonCode>r){switch(j.status()){case ARCHIVED->r.add(RuleReasonCode.JOB_ARCHIVED);case EXPIRED->r.add(RuleReasonCode.JOB_EXPIRED);case DUPLICATE->r.add(RuleReasonCode.JOB_DUPLICATE);case SOURCE_REMOVED->r.add(RuleReasonCode.JOB_SOURCE_REMOVED);default->{}}if(j.expiresAt()!=null&&j.expiresAt().isBefore(Instant.now())&&!r.contains(RuleReasonCode.JOB_EXPIRED))r.add(RuleReasonCode.JOB_EXPIRED);}
 private static void matchTerms(String value,JsonNode terms,RuleReasonCode code,String key,List<RuleReasonCode>reasons,Map<String,String>evidence){if(value==null||!terms.isArray())return;for(var n:terms){String term=n.asText().trim();if(!term.isEmpty()&&Pattern.compile("(?iu)(?<![\\p{L}\\p{N}])"+Pattern.quote(term)+"(?![\\p{L}\\p{N}])").matcher(value).find()){reasons.add(code);evidence.putIfAbsent(key,term);return;}}}
 private RuleEvaluationResponse map(JobRuleEvaluation e,boolean hit){try{return new RuleEvaluationResponse(e.id,e.jobId,e.profileVersionId,e.rulesetVersion,e.result,mapper.readValue(e.reasonCodes,new TypeReference<>(){}),mapper.readValue(e.safeEvidence,new TypeReference<>(){}),hit,e.createdAt);}catch(Exception x){throw new IllegalStateException("Stored rule result is invalid",x);}}
}
