package com.amit.jobagent.matching;
import com.amit.jobagent.common.persistence.MutableEntity;import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;import org.hibernate.annotations.JdbcTypeCode;import org.hibernate.type.SqlTypes;
@Entity @Table(name="job_evaluation") class JobEvaluation extends MutableEntity{
 @Column(name="job_id",nullable=false)UUID jobId;@Column(name="profile_version_id",nullable=false)UUID profileVersionId;@Column(name="rule_evaluation_id")UUID ruleEvaluationId;@Column(name="llm_execution_id")UUID llmExecutionId;@Column(name="run_id")UUID runId;@Enumerated(EnumType.STRING)@Column(nullable=false)EvaluationStatus status;@Enumerated(EnumType.STRING)Recommendation recommendation;@Column(name="overall_score")Integer overallScore;@Column(name="skills_score")Integer skillsScore;@Column(name="experience_score")Integer experienceScore;@Column(name="role_score")Integer roleScore;@Column(name="location_score")Integer locationScore;@Column(name="domain_score")Integer domainScore;@Column(name="compensation_score")Integer compensationScore;Integer confidence;
 @JdbcTypeCode(SqlTypes.JSON)@Column(name="matched_skills",columnDefinition="jsonb")String matchedSkills="[]";@JdbcTypeCode(SqlTypes.JSON)@Column(name="missing_required_skills",columnDefinition="jsonb")String missingRequiredSkills="[]";@JdbcTypeCode(SqlTypes.JSON)@Column(name="missing_preferred_skills",columnDefinition="jsonb")String missingPreferredSkills="[]";@JdbcTypeCode(SqlTypes.JSON)@Column(columnDefinition="jsonb")String risks="[]";@JdbcTypeCode(SqlTypes.JSON)@Column(name="questions_needing_user_input",columnDefinition="jsonb")String questions="[]";String summary;@JdbcTypeCode(SqlTypes.JSON)@Column(name="structured_output_json",columnDefinition="jsonb")String output;@JdbcTypeCode(SqlTypes.JSON)@Column(name="unassessed_dimensions",columnDefinition="jsonb")String unassessed="[]";
 @JdbcTypeCode(SqlTypes.CHAR)@Column(name="job_content_hash",nullable=false,length=64,columnDefinition="char(64)")String jobHash;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="profile_snapshot_checksum",nullable=false,length=64,columnDefinition="char(64)")String profileHash;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="matching_configuration_checksum",nullable=false,length=64,columnDefinition="char(64)")String configHash;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="prompt_checksum",nullable=false,length=64,columnDefinition="char(64)")String promptHash;@JdbcTypeCode(SqlTypes.CHAR)@Column(name="schema_checksum",nullable=false,length=64,columnDefinition="char(64)")String schemaHash;@Column(name="evaluation_cache_key",length=64)String cacheKey;boolean stale;@Column(name="safe_error_code")String errorCode;@Column(name="safe_error_message")String errorMessage;@Column(name="completed_at")Instant completedAt;
 protected JobEvaluation(){}JobEvaluation(UUID job,UUID profile,UUID rule,String jobHash,String profileHash,String configHash,String promptHash,String schemaHash,String cacheKey){this.jobId=job;profileVersionId=profile;ruleEvaluationId=rule;this.jobHash=jobHash;this.profileHash=profileHash;this.configHash=configHash;this.promptHash=promptHash;this.schemaHash=schemaHash;this.cacheKey=cacheKey;status=EvaluationStatus.QUEUED;}
 void filtered(){status=EvaluationStatus.RULE_FILTERED;recommendation=Recommendation.SKIP;overallScore=0;completedAt=Instant.now();}void unavailable(String code){status=EvaluationStatus.NEEDS_REVIEW;recommendation=Recommendation.MANUAL_REVIEW;errorCode=code;errorMessage="AI evaluation is unavailable; deterministic result remains available";completedAt=Instant.now();}
}
