package com.amit.jobagent.matching;
import com.amit.jobagent.ai.*;import com.amit.jobagent.audit.*;import com.amit.jobagent.job.*;import com.amit.jobagent.profile.version.*;import com.fasterxml.jackson.databind.ObjectMapper;import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class JobEvaluationService{
 private final JobMatchingProvider jobs;private final PublishedProfileProvider profiles;private final MatchingConfigurationService configs;private final DeterministicRuleService rules;private final JobEvaluationRepository repo;private final AiEvaluationProperties ai;private final PromptCatalog prompts;private final AuditService audit;
 public JobEvaluationService(JobMatchingProvider j,PublishedProfileProvider p,MatchingConfigurationService c,DeterministicRuleService r,JobEvaluationRepository e,AiEvaluationProperties ai,PromptCatalog prompts,AuditService audit){jobs=j;profiles=p;configs=c;rules=r;repo=e;this.ai=ai;this.prompts=prompts;this.audit=audit;}
 @Transactional public JobEvaluationResponse submit(UUID jobId,boolean force){var j=jobs.require(jobId);var p=profiles.requireActive();var c=configs.get();var rule=rules.evaluate(j,p,c.rulesetVersion());String configHash=PromptCatalog.hash(c.toString());String key=PromptCatalog.hash(String.join("|",j.contentHash(),p.checksum(),c.rulesetVersion(),configHash,prompts.promptChecksum,prompts.schemaChecksum,"OPENAI",ai.model()));if(!force){var hit=repo.findFirstByCacheKeyAndStatusIn(key,List.of(EvaluationStatus.SUCCEEDED,EvaluationStatus.NEEDS_REVIEW));if(hit.isPresent()){audit.record(AuditEventType.JOB_EVALUATION_CACHE_HIT,"JobEvaluation",hit.get().getId(),"{}");return map(hit.get());}}var e=new JobEvaluation(j.id(),p.id(),rule.id(),j.contentHash(),p.checksum(),configHash,prompts.promptChecksum,prompts.schemaChecksum,key);if(rule.result()==RuleResult.FAIL)e.filtered();else if(!ai.enabled())e.unavailable("AI_DISABLED");var saved=repo.saveAndFlush(e);audit.record(force?AuditEventType.JOB_EVALUATION_FORCE_REQUESTED:AuditEventType.JOB_EVALUATION_QUEUED,"JobEvaluation",saved.getId(),"{}");return map(saved);}
 @Transactional(readOnly=true)public List<JobEvaluationResponse>list(UUID job){return repo.findByJobIdOrderByCreatedAtDesc(job).stream().map(JobEvaluationService::map).toList();}@Transactional(readOnly=true)public JobEvaluationResponse get(UUID id){return map(repo.findById(id).orElseThrow(()->new com.amit.jobagent.common.error.ResourceNotFoundException("Evaluation was not found")));}
 private static JobEvaluationResponse map(JobEvaluation e){return new JobEvaluationResponse(e.getId(),e.jobId,e.profileVersionId,e.ruleEvaluationId,e.status,e.recommendation,e.overallScore,e.confidence,e.errorCode,e.errorMessage,e.stale,e.getCreatedAt(),e.completedAt);}
}
