package com.amit.jobagent.audit;
public enum AuditEventType {
    PROFILE_CREATED, PROFILE_UPDATED, PREFERENCES_UPDATED,
    RESUME_FACT_CREATED, RESUME_FACT_UPDATED, RESUME_FACT_VERIFIED, RESUME_FACT_REJECTED, RESUME_FACT_ARCHIVED,
    REUSABLE_ANSWER_VERIFIED, RESUME_DOCUMENT_UPLOADED, RESUME_DOCUMENT_ACTIVATED, RESUME_DOCUMENT_ARCHIVED,
    PROFILE_VERSION_PUBLISHED,
    JOB_SOURCE_CREATED, JOB_SOURCE_UPDATED, JOB_SOURCE_ENABLED, JOB_SOURCE_DISABLED, JOB_SOURCE_ARCHIVED,
    JOB_SOURCE_SYNC_STARTED, JOB_SOURCE_SYNC_COMPLETED, JOB_SOURCE_SYNC_FAILED,
    JOB_CREATED, JOB_UPDATED, JOB_MARKED_DUPLICATE, JOB_MANUALLY_EDITED, JOB_ARCHIVED, JOB_RESTORED,
    JOB_MARKED_EXPIRED, JOB_MARKED_SOURCE_REMOVED, EMAIL_ALERT_INGESTED,
    MATCHING_CONFIGURATION_UPDATED, RULE_EVALUATION_COMPLETED, JOB_EVALUATION_QUEUED,
    JOB_EVALUATION_STARTED, JOB_EVALUATION_CACHE_HIT, JOB_EVALUATION_COMPLETED,
    JOB_EVALUATION_FAILED, JOB_EVALUATION_FORCE_REQUESTED, AI_BUDGET_REJECTED,
    EVALUATION_FEEDBACK_CREATED, EVALUATION_FEEDBACK_UPDATED,
    APPLICATION_PACKAGE_REQUESTED, APPLICATION_PACKAGE_COMPLETED, APPLICATION_PACKAGE_FAILED,
    APPLICATION_PACKAGE_REGENERATED, APPLICATION_CONTENT_EDITED, APPLICATION_PACKAGE_VALIDATED,
    DOCUMENT_ARTIFACT_DOWNLOADED, APPLICATION_PACKAGE_ARCHIVED,
    APPLICATION_REVIEW_APPROVED, APPLICATION_REVIEW_CHANGES_REQUESTED,
    APPLICATION_REVIEW_REJECTED, APPLICATION_REVIEW_INVALIDATED,
    APPLICATION_HANDOFF_CREATED, APPLICATION_HANDOFF_LAUNCHED, APPLICATION_HANDOFF_BLOCKED,
    APPLICATION_SUBMISSION_REPORTED, APPLICATION_NOT_SUBMITTED, APPLICATION_HANDOFF_CANCELLED
}
