package com.amit.jobagent;
import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.amit.jobagent.document.ObjectStorage;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
@SpringBootTest(properties={"spring.jpa.hibernate.ddl-auto=create-drop","spring.flyway.enabled=false"})
@AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class Phase2ApiIntegrationTest {
 @Autowired MockMvc mvc;@Autowired ObjectMapper mapper;@MockBean ObjectStorage storage;
 private static final String USER="test-user",PASS="test-password";
 private String profileJson(Long version){return """
 {"fullName":"Fictional Candidate","email":"candidate@example.test","phone":"+1 555 010 2020","professionalTitle":"Software Engineer","professionalSummary":"Builds reliable fictional systems.","currentCompany":"Example Labs","currentLocation":"Example City","totalExperienceMonths":48,"noticePeriodDays":30,"servingNoticePeriod":false,"linkedinUrl":"https://example.test/in/candidate","githubUrl":"https://example.test/candidate","leetcodeUrl":"","portfolioUrl":"https://portfolio.example.test","recordVersion":%s}
 """.formatted(version==null?"null":version);}
 private JsonNode createProfile()throws Exception{return body(mvc.perform(put("/api/v1/profile").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(profileJson(null))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());}
 private JsonNode createPreferences()throws Exception{var json="{\"targetTitles\":[\"Engineer\",\" engineer \"],\"preferredLocations\":[\"Example City\"],\"excludedLocations\":[],\"requiredSkills\":[\"Java\"],\"preferredSkills\":[\"PostgreSQL\"],\"excludedCompanies\":[],\"excludedKeywords\":[],\"minimumExperienceYears\":2,\"maximumExperienceYears\":8,\"minimumMatchScore\":70,\"maximumDailyShortlist\":20,\"maximumDailyApplications\":5,\"remoteAllowed\":true,\"hybridAllowed\":true,\"onsiteAllowed\":false}";return body(mvc.perform(put("/api/v1/profile/preferences").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isOk()).andExpect(jsonPath("$.targetTitles",hasSize(1))).andReturn().getResponse().getContentAsString());}
 private JsonNode createFact()throws Exception{var json="{\"category\":\"PROJECT\",\"statement\":\"Built a fictional Java service\",\"company\":\"Example Labs\",\"startDate\":\"2025-01-01\",\"endDate\":\"2025-06-01\",\"skillTags\":[\"Java\",\" java \"],\"domainTags\":[\"Payments\"],\"sourceReference\":\"Portfolio\",\"evidenceText\":\"Reviewed project record\"}";return body(mvc.perform(post("/api/v1/resume-facts").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DRAFT")).andExpect(jsonPath("$.skillTags",hasSize(1))).andReturn().getResponse().getContentAsString());}
 private JsonNode body(String json)throws Exception{return mapper.readTree(json);}
 @Test void phaseTwoEndpointsRequireAuthentication()throws Exception{mvc.perform(get("/api/v1/auth/check")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/profile")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/profile/preferences")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/resume-facts")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/reusable-answers")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/resume-documents")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/profile/versions")).andExpect(status().isUnauthorized());}
 @Test void publishingMissingProfileOrPreferencesReturnsFieldSpecificUnprocessableEntity()throws Exception{var request="{\"changeReason\":\"Fictional readiness check\"}";mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.fieldErrors.profile").exists());createProfile();mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.fieldErrors.preferences").exists());}
 @Test void createsUpdatesValidatesAndLocksProfile()throws Exception{var p=createProfile();mvc.perform(put("/api/v1/profile").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(profileJson(p.get("recordVersion").asLong()))).andExpect(status().isOk()).andExpect(jsonPath("$.recordVersion").value(1));mvc.perform(put("/api/v1/profile").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(profileJson(0L))).andExpect(status().isConflict());mvc.perform(put("/api/v1/profile").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(profileJson(null).replace("https://portfolio.example.test","file:///secret"))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.fieldErrors.portfolioUrl").exists());}
 @Test void validatesAndNormalizesPreferences()throws Exception{createProfile();createPreferences();var invalid="{\"targetTitles\":[],\"preferredLocations\":[],\"excludedLocations\":[],\"requiredSkills\":[\"Java\"],\"preferredSkills\":[\"java\"],\"excludedCompanies\":[],\"excludedKeywords\":[],\"minimumExperienceYears\":9,\"maximumExperienceYears\":2,\"minimumMatchScore\":101,\"maximumDailyShortlist\":20,\"maximumDailyApplications\":5,\"remoteAllowed\":false,\"hybridAllowed\":false,\"onsiteAllowed\":false}";mvc.perform(put("/api/v1/profile/preferences").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(invalid)).andExpect(status().isBadRequest());}
 @Test void enforcesResumeFactLifecycleAndFiltering()throws Exception{createProfile();var f=createFact();var id=f.get("id").asText();mvc.perform(post("/api/v1/resume-facts/{id}/verify",id).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("VERIFIED"));var edit="{\"category\":\"PROJECT\",\"statement\":\"Edited verified statement\",\"skillTags\":[\"Java\"],\"domainTags\":[],\"recordVersion\":1}";mvc.perform(put("/api/v1/resume-facts/{id}",id).with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(edit)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DRAFT"));mvc.perform(post("/api/v1/resume-facts/{id}/reject",id).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(post("/api/v1/resume-facts/{id}/restore-draft",id).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(get("/api/v1/resume-facts").with(httpBasic(USER,PASS)).param("skillTag","java").param("search","edited")).andExpect(status().isOk()).andExpect(jsonPath("$.content",hasSize(1)));mvc.perform(post("/api/v1/resume-facts/{id}/archive",id).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(post("/api/v1/resume-facts/{id}/verify",id).with(httpBasic(USER,PASS))).andExpect(status().isBadRequest());}
 @Test void importSkipsExactDuplicatesAndNeverVerifies()throws Exception{createProfile();var candidate="{\"category\":\"SKILL\",\"statement\":\"Uses fictional tooling\",\"skillTags\":[\"Tool\"],\"domainTags\":[]}";mvc.perform(post("/api/v1/resume-facts/import").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("["+candidate+","+candidate+"]")).andExpect(status().isOk()).andExpect(jsonPath("$.importedCount").value(1)).andExpect(jsonPath("$.duplicateIndexes[0]").value(1));}
 @Test void answerRulesAndLifecycleAreEnforced()throws Exception{createProfile();var invalid="{\"question\":\"Expected compensation?\",\"answer\":\"Fictional amount\",\"category\":\"COMPENSATION\",\"sensitivity\":\"SAFE_AUTOFILL\"}";mvc.perform(post("/api/v1/reusable-answers").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(invalid)).andExpect(status().isBadRequest());var valid=invalid.replace("COMPENSATION","WORK_AUTHORIZATION").replace("SAFE_AUTOFILL","REQUIRES_REVIEW");var a=body(mvc.perform(post("/api/v1/reusable-answers").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(valid)).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DRAFT")).andReturn().getResponse().getContentAsString());var id=a.get("id").asText();mvc.perform(post("/api/v1/reusable-answers/{id}/verify",id).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(put("/api/v1/reusable-answers/{id}",id).with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(valid.substring(0,valid.length()-1)+",\"recordVersion\":1}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DRAFT"));mvc.perform(post("/api/v1/reusable-answers",id).with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(valid)).andExpect(status().isConflict());}
 @Test void uploadsExtractsActivatesAndDownloadsPdfAndDocx()throws Exception{createProfile();var pdf=new MockMultipartFile("file","../fictional resume.pdf","application/pdf",pdfBytes());var uploaded=body(mvc.perform(multipart("/api/v1/resume-documents").file(pdf).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.sanitizedFileName").value("fictional_resume.pdf")).andExpect(jsonPath("$.extractedTextAvailable").value(true)).andReturn().getResponse().getContentAsString());var id=uploaded.get("id").asText();when(storage.load(anyString())).thenReturn(pdf.getBytes());mvc.perform(post("/api/v1/resume-documents/{id}/activate",id).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.active").value(true));mvc.perform(get("/api/v1/resume-documents/{id}/download",id).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(content().bytes(pdf.getBytes()));var docx=new MockMultipartFile("file","second.docx",DOCX,docxBytes());mvc.perform(multipart("/api/v1/resume-documents").file(docx).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.extractedTextAvailable").value(true));}
 @Test void rejectsMismatchedDocumentAndStorageFailure()throws Exception{createProfile();var bad=new MockMultipartFile("file","resume.pdf","application/pdf","not pdf".getBytes());mvc.perform(multipart("/api/v1/resume-documents").file(bad).with(httpBasic(USER,PASS))).andExpect(status().isUnsupportedMediaType());doThrow(new com.amit.jobagent.common.error.StorageUnavailableException("down",new RuntimeException())).when(storage).store(anyString(),any(),anyString());var pdf=new MockMultipartFile("file","resume.pdf","application/pdf",pdfBytes());mvc.perform(multipart("/api/v1/resume-documents").file(pdf).with(httpBasic(USER,PASS))).andExpect(status().isServiceUnavailable());}
 @Test void rejectsInvalidFactDatesAndOversizedDocuments()throws Exception{createProfile();var invalidDate="{\"category\":\"EMPLOYMENT\",\"statement\":\"Fictional employment\",\"startDate\":\"2026-02-01\",\"endDate\":\"2026-01-01\",\"skillTags\":[],\"domainTags\":[]}";mvc.perform(post("/api/v1/resume-facts").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(invalidDate)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.fieldErrors.endDate").exists());var oversized=new MockMultipartFile("file","large.pdf","application/pdf",new byte[5_242_881]);mvc.perform(multipart("/api/v1/resume-documents").file(oversized).with(httpBasic(USER,PASS))).andExpect(status().isPayloadTooLarge());}
 @Test void preventsDuplicateDocumentsAndKeepsOnlyOneActiveMaster()throws Exception{createProfile();var pdfBytes=pdfBytes();var first=body(mvc.perform(multipart("/api/v1/resume-documents").file(new MockMultipartFile("file","first.pdf","application/pdf",pdfBytes)).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());mvc.perform(multipart("/api/v1/resume-documents").file(new MockMultipartFile("file","duplicate.pdf","application/pdf",pdfBytes)).with(httpBasic(USER,PASS))).andExpect(status().isConflict());var second=body(mvc.perform(multipart("/api/v1/resume-documents").file(new MockMultipartFile("file","second.docx",DOCX,docxBytes())).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/v1/resume-documents/{id}/activate",first.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(post("/api/v1/resume-documents/{id}/activate",second.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(get("/api/v1/resume-documents").with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$[?(@.active == true)]",hasSize(1)));mvc.perform(get("/api/v1/resume-documents/{id}",first.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(jsonPath("$.active").value(false));mvc.perform(get("/api/v1/resume-documents/{id}",second.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(jsonPath("$.active").value(true));}
 @Test void publishesDeterministicVerifiedSnapshotWithoutDuplicates()throws Exception{createProfile();createPreferences();var fact=createFact();var factId=fact.get("id").asText();mvc.perform(post("/api/v1/resume-facts/{id}/verify",factId).with(httpBasic(USER,PASS))).andExpect(status().isOk());var pdf=new MockMultipartFile("file","resume.pdf","application/pdf",pdfBytes());var doc=body(mvc.perform(multipart("/api/v1/resume-documents").file(pdf).with(httpBasic(USER,PASS))).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/v1/resume-documents/{id}/activate",doc.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());var request="{\"changeReason\":\"Initial fictional profile\"}";var first=body(mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isOk()).andExpect(jsonPath("$.snapshot.verifiedResumeFacts",hasSize(1))).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("{\"changeReason\":\"No content change\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.unchanged").value(true)).andExpect(jsonPath("$.checksum").value(first.get("checksum").asText()));mvc.perform(get("/api/v1/profile/versions").with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$",hasSize(1)));}
 @Test void publicationIsSequentialAndExcludesArchivedFacts()throws Exception{createProfile();createPreferences();var firstFact=createFact();mvc.perform(post("/api/v1/resume-facts/{id}/verify",firstFact.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());var document=body(mvc.perform(multipart("/api/v1/resume-documents").file(new MockMultipartFile("file","resume.pdf","application/pdf",pdfBytes())).with(httpBasic(USER,PASS))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/v1/resume-documents/{id}/activate",document.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());var first=body(mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("{\"changeReason\":\"Version one\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());var secondFact=body(mvc.perform(post("/api/v1/resume-facts").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("{\"category\":\"ACHIEVEMENT\",\"statement\":\"Won a fictional reliability award\",\"skillTags\":[],\"domainTags\":[]}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());mvc.perform(post("/api/v1/resume-facts/{id}/verify",secondFact.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());var second=body(mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("{\"changeReason\":\"Version two\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.versionNumber").value(2)).andExpect(jsonPath("$.snapshot.verifiedResumeFacts",hasSize(2))).andReturn().getResponse().getContentAsString());assertThat(second.get("checksum").asText()).isNotEqualTo(first.get("checksum").asText());mvc.perform(post("/api/v1/resume-facts/{id}/archive",secondFact.get("id").asText()).with(httpBasic(USER,PASS))).andExpect(status().isOk());mvc.perform(post("/api/v1/profile/publish").with(httpBasic(USER,PASS)).contentType(MediaType.APPLICATION_JSON).content("{\"changeReason\":\"Archived second fact\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.versionNumber").value(3)).andExpect(jsonPath("$.checksum").value(first.get("checksum").asText())).andExpect(jsonPath("$.snapshot.verifiedResumeFacts",hasSize(1)));mvc.perform(get("/api/v1/profile/versions/active").with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.versionNumber").value(3));mvc.perform(get("/api/v1/profile/versions/1").with(httpBasic(USER,PASS))).andExpect(status().isOk()).andExpect(jsonPath("$.active").value(false));}
 private static final String DOCX="application/vnd.openxmlformats-officedocument.wordprocessingml.document";
 private static byte[] pdfBytes()throws Exception{try(var document=new PDDocument();var output=new ByteArrayOutputStream()){var page=new PDPage();document.addPage(page);try(var content=new PDPageContentStream(document,page)){content.beginText();content.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA),12);content.newLineAtOffset(50,700);content.showText("Fictional candidate resume");content.endText();}document.save(output);return output.toByteArray();}}
 private static byte[] docxBytes()throws Exception{try(var document=new XWPFDocument();var output=new ByteArrayOutputStream()){document.createParagraph().createRun().setText("Fictional DOCX resume");document.write(output);return output.toByteArray();}}
}
