import axios from 'axios'
import { Alert,Button,Checkbox,FormControlLabel,Grid,Paper,Stack,TextField,Typography } from '@mui/material'
import { useEffect,useState,type FormEvent } from 'react'
import { profileApi } from '../api/profileApi'
import type { CandidateProfileInput } from '../types/profile'
const empty:CandidateProfileInput={fullName:'',email:'',phone:'',professionalTitle:'',professionalSummary:'',currentCompany:'',currentLocation:'',totalExperienceMonths:0,noticePeriodDays:0,servingNoticePeriod:false,linkedinUrl:'',githubUrl:'',leetcodeUrl:'',portfolioUrl:''}
export function ProfilePage(){const[form,setForm]=useState(empty);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[error,setError]=useState('')
 useEffect(()=>{profileApi.getProfile().then(p=>setForm(p),e=>{if(!axios.isAxiosError(e)||e.response?.status!==404)setError('Could not load profile')}).finally(()=>setLoading(false))},[])
 const field=(name:keyof CandidateProfileInput,value:string|number|boolean)=>setForm(v=>({...v,[name]:value}))
 const save=async(e:FormEvent)=>{e.preventDefault();setError('');setMessage('');if(!form.fullName.trim()||!form.email.includes('@')||!form.professionalTitle.trim()){setError('Full name, valid email, and professional title are required');return}try{setForm(await profileApi.saveProfile(form));setMessage('Profile saved')}catch(err){setError(axios.isAxiosError(err)&&err.response?.status===409?'This profile changed elsewhere. Reload before saving.':'Profile could not be saved') }}
 if(loading)return <Typography>Loading profile…</Typography>
 const textFields:[keyof CandidateProfileInput,string,boolean?][]=[['fullName','Full name'],['email','Email'],['phone','Phone'],['professionalTitle','Professional title'],['currentCompany','Current company'],['currentLocation','Current location'],['professionalSummary','Professional summary',true],['linkedinUrl','LinkedIn URL'],['githubUrl','GitHub URL'],['leetcodeUrl','LeetCode URL'],['portfolioUrl','Portfolio URL']]
 return <Stack spacing={3}><div><Typography variant="h4">Candidate profile</Typography><Typography color="text.secondary">Mutable private details used to create verified snapshots.</Typography></div>{error&&<Alert severity="error">{error}</Alert>}{message&&<Alert severity="success">{message}</Alert>}<Paper component="form" onSubmit={save} sx={{p:3}}><Grid container spacing={2}>{textFields.map(([name,label,multi])=><Grid key={name} size={{xs:12,md:multi?12:6}}><TextField fullWidth label={label} multiline={multi} minRows={multi?4:undefined} value={String(form[name]??'')} onChange={e=>field(name,e.target.value)}/></Grid>)}<Grid size={{xs:12,md:4}}><TextField fullWidth type="number" label="Experience (months)" value={form.totalExperienceMonths} onChange={e=>field('totalExperienceMonths',Number(e.target.value))}/></Grid><Grid size={{xs:12,md:4}}><TextField fullWidth type="number" label="Notice period (days)" value={form.noticePeriodDays} onChange={e=>field('noticePeriodDays',Number(e.target.value))}/></Grid><Grid size={{xs:12,md:4}}><FormControlLabel control={<Checkbox checked={form.servingNoticePeriod} onChange={e=>field('servingNoticePeriod',e.target.checked)}/>} label="Serving notice period"/></Grid><Grid size={12}><Button type="submit" variant="contained">Save profile</Button></Grid></Grid></Paper></Stack>}
