import { Alert,Button,Chip,LinearProgress,Paper,Stack,Typography } from '@mui/material'
import { useCallback,useEffect,useState } from 'react'
import { profileApi } from '../api/profileApi'
import type { ResumeDocument } from '../types/profile'
export function ResumeDocumentsPage(){const[items,setItems]=useState<ResumeDocument[]>([]);const[error,setError]=useState('');const[progress,setProgress]=useState<number|null>(null);const[preview,setPreview]=useState('');const load=useCallback(()=>profileApi.documents().then(setItems,()=>setError('Could not load resume documents')),[]);useEffect(()=>{void load()},[load])
 const upload=async(file?:File)=>{if(!file)return;setError('');if(!/\.(pdf|docx)$/i.test(file.name)){setError('Select a PDF or DOCX file');return}if(file.size>5*1024*1024){setError('The document exceeds 5 MB');return}try{setProgress(0);await profileApi.upload(file,setProgress);await load()}catch{setError('Upload failed. The file may not match its extension or may be a duplicate.')}finally{setProgress(null)}}
 const action=async(id:string,a:string)=>{try{await profileApi.documentAction(id,a);await load()}catch{setError('Document action failed')}}
 const text=async(id:string)=>{try{const result=await profileApi.extractedText(id);setPreview(result.extractedText||result.extractionError||'No extracted text is available')}catch{setError('Could not load extracted text')}}
 const download=async(d:ResumeDocument)=>{try{const blob=await profileApi.download(d.id);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=d.sanitizedFileName;link.click();URL.revokeObjectURL(url)}catch{setError('Download failed')}}
 return <Stack spacing={3}><Typography variant="h4">Master resume documents</Typography><Typography color="text.secondary">Original files stay private in MinIO. Extracted text is never converted into facts automatically.</Typography>{error&&<Alert severity="error">{error}</Alert>}<Button component="label" variant="contained">Upload PDF or DOCX<input hidden type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>void upload(e.target.files?.[0])}/></Button>{progress!==null&&<LinearProgress variant="determinate" value={progress}/>} {items.length===0?<Typography color="text.secondary">No resume documents uploaded.</Typography>:items.map(d=><Paper key={d.id} variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between"><div><Stack direction="row" spacing={1}><Chip label={d.status}/>{d.active&&<Chip color="success" label="Active master resume"/>}</Stack><Typography variant="h6" sx={{mt:1}}>{d.originalFileName}</Typography><Typography variant="body2">{Math.round(d.sizeBytes/1024)} KB · SHA-256 {d.sha256Checksum}</Typography>{d.extractionError&&<Alert severity="warning" sx={{mt:1}}>{d.extractionError}</Alert>}</div><Stack direction="row" flexWrap="wrap"><Button onClick={()=>void download(d)}>Download</Button>{d.extractedTextAvailable&&<Button onClick={()=>void text(d.id)}>Preview text</Button>}{!d.active&&d.status!=='ARCHIVED'&&<Button onClick={()=>void action(d.id,'activate')}>Activate</Button>}{d.status!=='ARCHIVED'&&<Button color="warning" onClick={()=>void action(d.id,'archive')}>Archive</Button>}</Stack></Stack></Paper>)}{preview&&<Paper variant="outlined" sx={{p:2}}><Typography variant="h6">Extracted text preview</Typography><Typography component="pre" sx={{whiteSpace:'pre-wrap',fontFamily:'inherit',maxHeight:400,overflow:'auto'}}>{preview}</Typography></Paper>}</Stack>}
