import { Alert,Button,Chip,Grid,MenuItem,Paper,Stack,TextField,Typography } from '@mui/material'
import { useCallback,useEffect,useState,type FormEvent } from 'react'
import { profileApi } from '../api/profileApi'
import type { ReusableAnswer } from '../types/profile'
const categories=['GENERAL','EXPERIENCE','NOTICE_PERIOD','COMPENSATION','WORK_AUTHORIZATION','RELOCATION','DEMOGRAPHIC','LEGAL','OTHER'];const sensitivities=['SAFE_AUTOFILL','REQUIRES_REVIEW','NEVER_AUTOFILL'];const empty={question:'',answer:'',category:'GENERAL',sensitivity:'REQUIRES_REVIEW'}
export function ReusableAnswersPage(){const[items,setItems]=useState<ReusableAnswer[]>([]);const[form,setForm]=useState(empty);const[editing,setEditing]=useState<ReusableAnswer|null>(null);const[error,setError]=useState('');const load=useCallback(()=>profileApi.answers().then(setItems,()=>setError('Could not load reusable answers')),[]);useEffect(()=>{void load()},[load]);const sensitive=['COMPENSATION','DEMOGRAPHIC','LEGAL'].includes(form.category)
 const save=async(e:FormEvent)=>{e.preventDefault();try{const body={...form,recordVersion:editing?.recordVersion};if(editing)await profileApi.updateAnswer(editing.id,body);else await profileApi.createAnswer(body);setEditing(null);setForm(empty);await load()}catch{setError('Answer could not be saved; check duplicate and sensitivity rules')}}
 const edit=(a:ReusableAnswer)=>{setEditing(a);setForm({question:a.question,answer:a.answer,category:a.category,sensitivity:a.sensitivity})};const action=async(id:string,a:string)=>{try{await profileApi.answerAction(id,a);await load()}catch{setError('That answer transition is not allowed')}}
 return <Stack spacing={3}><Typography variant="h4">Reusable application answers</Typography>{error&&<Alert severity="error">{error}</Alert>}<Paper component="form" onSubmit={save} sx={{p:3}}><Typography variant="h6">{editing?'Edit answer':'Create draft answer'}</Typography>{editing?.status==='VERIFIED'&&<Alert severity="warning" sx={{my:2}}>Editing resets this answer to draft.</Alert>}{sensitive&&<Alert severity="warning" sx={{my:2}}>This sensitive category can never be marked safe for autofill.</Alert>}<Grid container spacing={2} sx={{mt:1}}><Grid size={12}><TextField fullWidth required label="Question" value={form.question} onChange={e=>setForm(v=>({...v,question:e.target.value}))}/></Grid><Grid size={12}><TextField fullWidth required multiline minRows={3} label="Answer" value={form.answer} onChange={e=>setForm(v=>({...v,answer:e.target.value}))}/></Grid><Grid size={{xs:12,md:6}}><TextField select fullWidth label="Category" value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}>{categories.map(c=><MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:6}}><TextField select fullWidth label="Sensitivity" value={form.sensitivity} onChange={e=>setForm(v=>({...v,sensitivity:e.target.value}))}>{sensitivities.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid><Grid size={12}><Button type="submit" variant="contained">Save answer</Button>{editing&&<Button onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</Button>}</Grid></Grid></Paper>{items.length===0?<Typography color="text.secondary">No reusable answers yet.</Typography>:items.map(a=><Paper key={a.id} variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between"><div><Stack direction="row" spacing={1}><Chip label={a.status} color={a.status==='VERIFIED'?'success':'default'}/><Chip label={a.sensitivity} color={a.sensitivity==='NEVER_AUTOFILL'?'error':'default'}/></Stack><Typography variant="h6" sx={{mt:1}}>{a.question}</Typography><Typography sx={{whiteSpace:'pre-wrap'}}>{a.answer}</Typography></div><Stack direction="row"><Button onClick={()=>edit(a)}>Edit</Button>{a.status==='DRAFT'&&<Button onClick={()=>void action(a.id,'verify')}>Verify</Button>}{a.status==='ARCHIVED'?<Button onClick={()=>void action(a.id,'restore-draft')}>Restore</Button>:<Button color="warning" onClick={()=>void action(a.id,'archive')}>Archive</Button>}</Stack></Stack></Paper>)}</Stack>}
