import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { profileApi } from '../api/profileApi'
import { ProfilePage } from '../pages/ProfilePage'
import { PreferencesPage } from '../pages/PreferencesPage'
import { ReusableAnswersPage } from '../pages/ReusableAnswersPage'
import { ResumeDocumentsPage } from '../pages/ResumeDocumentsPage'
import { ProfileVersionsPage } from '../pages/ProfileVersionsPage'
const profile={id:'p',fullName:'Fictional Candidate',email:'candidate@example.test',professionalTitle:'Engineer',totalExperienceMonths:12,noticePeriodDays:30,servingNoticePeriod:false,recordVersion:0,createdAt:'2026-01-01',updatedAt:'2026-01-01'}
beforeEach(()=>vi.restoreAllMocks())
describe('Phase 2 pages',()=>{
 it('loads and saves a profile',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);const save=vi.spyOn(profileApi,'saveProfile').mockResolvedValue(profile);render(<ProfilePage/>);expect(await screen.findByDisplayValue('Fictional Candidate')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Save profile'}));await waitFor(()=>expect(save).toHaveBeenCalled())})
 it('does not send response-only profile fields when saving',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);const save=vi.spyOn(profileApi,'saveProfile').mockResolvedValue(profile);render(<ProfilePage/>);await screen.findByDisplayValue('Fictional Candidate');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));await waitFor(()=>expect(save).toHaveBeenCalled());const request=save.mock.calls[0][0] as Record<string,unknown>;expect(request).toMatchObject({fullName:'Fictional Candidate',recordVersion:0});expect(request).not.toHaveProperty('id');expect(request).not.toHaveProperty('createdAt');expect(request).not.toHaveProperty('updatedAt')})
 it('explains an optimistic-lock conflict',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);vi.spyOn(profileApi,'saveProfile').mockRejectedValue({isAxiosError:true,response:{status:409}});render(<ProfilePage/>);await screen.findByDisplayValue('Fictional Candidate');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText(/changed elsewhere/i)).toBeInTheDocument()})
 it('shows the backend profile validation message',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);vi.spyOn(profileApi,'saveProfile').mockRejectedValue({isAxiosError:true,response:{status:400,data:{fieldErrors:{portfolioUrl:'must use http or https'}}}});render(<ProfilePage/>);await screen.findByDisplayValue('Fictional Candidate');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText('must use http or https')).toBeInTheDocument()})
 it('validates profile before save',async()=>{vi.spyOn(profileApi,'getProfile').mockRejectedValue({response:{status:404}});render(<ProfilePage/>);await screen.findByLabelText('Full name');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText(/valid email/i)).toBeInTheDocument()})
 it('edits preferences and preserves spaces while typing',async()=>{vi.spyOn(profileApi,'getPreferences').mockRejectedValue({response:{status:404}});const save=vi.spyOn(profileApi,'savePreferences').mockResolvedValue({profileId:'p',targetTitles:['Java Backend Developer'],preferredLocations:[],excludedLocations:[],requiredSkills:[],preferredSkills:[],excludedCompanies:[],excludedKeywords:[],minimumExperienceYears:0,maximumExperienceYears:10,minimumMatchScore:60,maximumDailyShortlist:20,maximumDailyApplications:5,remoteAllowed:true,hybridAllowed:true,onsiteAllowed:true,recordVersion:0});render(<PreferencesPage/>);const titles=await screen.findByLabelText('Target titles');fireEvent.change(titles,{target:{value:'Java Backend Developer, java backend developer'}});expect(titles).toHaveValue('Java Backend Developer, java backend developer');fireEvent.click(screen.getByRole('button',{name:'Save preferences'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({targetTitles:['Java Backend Developer']})))})
 it('updates preferences without sending response-only fields',async()=>{const existing={profileId:'p',targetTitles:['Senior Backend Developer'],preferredLocations:['Noida'],excludedLocations:[],requiredSkills:['Java'],preferredSkills:['Spring Boot'],excludedCompanies:[],excludedKeywords:[],minimumExperienceYears:4,maximumExperienceYears:6,minimumMatchScore:75,maximumDailyShortlist:20,maximumDailyApplications:20,remoteAllowed:true,hybridAllowed:true,onsiteAllowed:true,recordVersion:3,createdAt:'2026-01-01',updatedAt:'2026-01-02'};vi.spyOn(profileApi,'getPreferences').mockResolvedValue(existing);const save=vi.spyOn(profileApi,'savePreferences').mockResolvedValue(existing);render(<PreferencesPage/>);await screen.findByDisplayValue('Senior Backend Developer');fireEvent.click(screen.getByRole('button',{name:'Save preferences'}));await waitFor(()=>expect(save).toHaveBeenCalled());const request=save.mock.calls[0][0] as Record<string,unknown>;expect(request).toMatchObject({targetTitles:['Senior Backend Developer'],recordVersion:3});expect(request).not.toHaveProperty('profileId');expect(request).not.toHaveProperty('createdAt');expect(request).not.toHaveProperty('updatedAt')})
 it('shows the backend preference validation message',async()=>{vi.spyOn(profileApi,'getPreferences').mockRejectedValue({response:{status:404}});vi.spyOn(profileApi,'savePreferences').mockRejectedValue({isAxiosError:true,response:{status:400,data:{fieldErrors:{preferredSkills:'A skill cannot be both required and preferred'}}}});render(<PreferencesPage/>);fireEvent.change(await screen.findByLabelText('Target titles'),{target:{value:'Java Backend Developer'}});fireEvent.change(screen.getByLabelText('Required skills'),{target:{value:'Java'}});fireEvent.change(screen.getByLabelText('Preferred skills'),{target:{value:'Java'}});fireEvent.click(screen.getByRole('button',{name:'Save preferences'}));expect(await screen.findByText('A skill cannot be both required and preferred')).toBeInTheDocument()})
 it('shows reusable-answer sensitivity warning',async()=>{vi.spyOn(profileApi,'answers').mockResolvedValue([]);render(<ReusableAnswersPage/>);await screen.findByText('No reusable answers yet.');fireEvent.mouseDown(screen.getByLabelText('Category'));fireEvent.click(await screen.findByText('COMPENSATION'));expect(screen.getByText(/never be marked safe/i)).toBeInTheDocument()})
 it('rejects invalid document extensions in the browser',async()=>{vi.spyOn(profileApi,'documents').mockResolvedValue([]);render(<ResumeDocumentsPage/>);await screen.findByText('No resume documents uploaded.');const input=document.querySelector('input[type=file]') as HTMLInputElement;fireEvent.change(input,{target:{files:[new File(['x'],'resume.txt',{type:'text/plain'})]}});expect(await screen.findByText('Select a PDF or DOCX file')).toBeInTheDocument()})
 it('renders extracted text as plain text',async()=>{vi.spyOn(profileApi,'documents').mockResolvedValue([{id:'d',originalFileName:'resume.pdf',sanitizedFileName:'resume.pdf',contentType:'application/pdf',sizeBytes:10,sha256Checksum:'abc',status:'TEXT_EXTRACTED',active:true,extractedTextAvailable:true}]);vi.spyOn(profileApi,'extractedText').mockResolvedValue({extractedText:'<img src=x onerror=alert(1)>'});render(<ResumeDocumentsPage/>);fireEvent.click(await screen.findByRole('button',{name:'Preview text'}));expect(await screen.findByText('<img src=x onerror=alert(1)>')).toBeInTheDocument();expect(document.querySelector('img')).toBeNull()})
 it('lists automatic immutable resume snapshots without a publish action',async()=>{vi.spyOn(profileApi,'versions').mockResolvedValue([{id:'v',versionNumber:1,snapshot:{profile:{fullName:'Fictional Candidate'}},checksum:'abc',changeReason:'Automatic snapshot from active resume',active:true,createdAt:'2026-01-01',unchanged:false}]);render(<ProfileVersionsPage/>);expect(await screen.findByText('Snapshot 1')).toBeInTheDocument();expect(screen.getByText(/do not need to publish/i)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Publish profile'})).not.toBeInTheDocument()})
 it('guides the user to evaluate a job when no snapshot exists',async()=>{vi.spyOn(profileApi,'versions').mockResolvedValue([]);render(<ProfileVersionsPage/>);expect(await screen.findByText(/Activate a resume and evaluate a job/i)).toBeInTheDocument()})
})
