import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { profileApi } from '../api/profileApi'
import { ProfilePage } from '../pages/ProfilePage'
import { PreferencesPage } from '../pages/PreferencesPage'
import { ResumeFactsPage } from '../pages/ResumeFactsPage'
import { ReusableAnswersPage } from '../pages/ReusableAnswersPage'
import { ResumeDocumentsPage } from '../pages/ResumeDocumentsPage'
import { ProfileVersionsPage } from '../pages/ProfileVersionsPage'
const profile={id:'p',fullName:'Fictional Candidate',email:'candidate@example.test',professionalTitle:'Engineer',totalExperienceMonths:12,noticePeriodDays:30,servingNoticePeriod:false,recordVersion:0,createdAt:'2026-01-01',updatedAt:'2026-01-01'}
beforeEach(()=>vi.restoreAllMocks())
describe('Phase 2 pages',()=>{
 it('loads and saves a profile',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);const save=vi.spyOn(profileApi,'saveProfile').mockResolvedValue(profile);render(<ProfilePage/>);expect(await screen.findByDisplayValue('Fictional Candidate')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Save profile'}));await waitFor(()=>expect(save).toHaveBeenCalled())})
 it('explains an optimistic-lock conflict',async()=>{vi.spyOn(profileApi,'getProfile').mockResolvedValue(profile);vi.spyOn(profileApi,'saveProfile').mockRejectedValue({isAxiosError:true,response:{status:409}});render(<ProfilePage/>);await screen.findByDisplayValue('Fictional Candidate');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText(/changed elsewhere/i)).toBeInTheDocument()})
 it('validates profile before save',async()=>{vi.spyOn(profileApi,'getProfile').mockRejectedValue({response:{status:404}});render(<ProfilePage/>);await screen.findByLabelText('Full name');fireEvent.click(screen.getByRole('button',{name:'Save profile'}));expect(await screen.findByText(/valid email/i)).toBeInTheDocument()})
 it('edits preferences and preserves spaces while typing',async()=>{vi.spyOn(profileApi,'getPreferences').mockRejectedValue({response:{status:404}});const save=vi.spyOn(profileApi,'savePreferences').mockResolvedValue({profileId:'p',targetTitles:['Java Backend Developer'],preferredLocations:[],excludedLocations:[],requiredSkills:[],preferredSkills:[],excludedCompanies:[],excludedKeywords:[],minimumExperienceYears:0,maximumExperienceYears:10,minimumMatchScore:60,maximumDailyShortlist:20,maximumDailyApplications:5,remoteAllowed:true,hybridAllowed:true,onsiteAllowed:true,recordVersion:0});render(<PreferencesPage/>);const titles=await screen.findByLabelText('Target titles');fireEvent.change(titles,{target:{value:'Java Backend Developer, java backend developer'}});expect(titles).toHaveValue('Java Backend Developer, java backend developer');fireEvent.click(screen.getByRole('button',{name:'Save preferences'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({targetTitles:['Java Backend Developer']})))})
 it('shows the backend preference validation message',async()=>{vi.spyOn(profileApi,'getPreferences').mockRejectedValue({response:{status:404}});vi.spyOn(profileApi,'savePreferences').mockRejectedValue({isAxiosError:true,response:{status:400,data:{fieldErrors:{preferredSkills:'A skill cannot be both required and preferred'}}}});render(<PreferencesPage/>);fireEvent.change(await screen.findByLabelText('Target titles'),{target:{value:'Java Backend Developer'}});fireEvent.change(screen.getByLabelText('Required skills'),{target:{value:'Java'}});fireEvent.change(screen.getByLabelText('Preferred skills'),{target:{value:'Java'}});fireEvent.click(screen.getByRole('button',{name:'Save preferences'}));expect(await screen.findByText('A skill cannot be both required and preferred')).toBeInTheDocument()})
 it('creates facts and warns before editing verified facts',async()=>{const fact={id:'f',category:'PROJECT',statement:'Built a fictional service',skillTags:['Java'],domainTags:[],status:'VERIFIED',sourceType:'MANUAL',recordVersion:1};vi.spyOn(profileApi,'facts').mockResolvedValue({content:[fact],page:0,size:10,totalElements:1,totalPages:1});render(<ResumeFactsPage/>);expect(await screen.findByText('Built a fictional service')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Edit'}));expect(screen.getByText(/reset verification/i)).toBeInTheDocument()})
 it('creates and verifies a draft fact',async()=>{const draft={id:'draft',category:'PROJECT',statement:'Delivered a fictional migration',skillTags:[],domainTags:[],status:'DRAFT',sourceType:'MANUAL',recordVersion:0};vi.spyOn(profileApi,'facts').mockResolvedValue({content:[draft],page:0,size:10,totalElements:1,totalPages:1});const create=vi.spyOn(profileApi,'createFact').mockResolvedValue(draft);const transition=vi.spyOn(profileApi,'factAction').mockResolvedValue({...draft,status:'VERIFIED'});render(<ResumeFactsPage/>);await screen.findByText(draft.statement);fireEvent.change(screen.getByRole('textbox',{name:/Verified statement candidate/i}),{target:{value:'A separate fictional fact'}});fireEvent.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(create).toHaveBeenCalledWith(expect.objectContaining({statement:'A separate fictional fact'})));fireEvent.click(screen.getByRole('button',{name:'Verify'}));await waitFor(()=>expect(transition).toHaveBeenCalledWith('draft','verify'))})
 it('shows reusable-answer sensitivity warning',async()=>{vi.spyOn(profileApi,'answers').mockResolvedValue([]);render(<ReusableAnswersPage/>);await screen.findByText('No reusable answers yet.');fireEvent.mouseDown(screen.getByLabelText('Category'));fireEvent.click(await screen.findByText('COMPENSATION'));expect(screen.getByText(/never be marked safe/i)).toBeInTheDocument()})
 it('rejects invalid document extensions in the browser',async()=>{vi.spyOn(profileApi,'documents').mockResolvedValue([]);render(<ResumeDocumentsPage/>);await screen.findByText('No resume documents uploaded.');const input=document.querySelector('input[type=file]') as HTMLInputElement;fireEvent.change(input,{target:{files:[new File(['x'],'resume.txt',{type:'text/plain'})]}});expect(await screen.findByText('Select a PDF or DOCX file')).toBeInTheDocument()})
 it('renders extracted text as plain text',async()=>{vi.spyOn(profileApi,'documents').mockResolvedValue([{id:'d',originalFileName:'resume.pdf',sanitizedFileName:'resume.pdf',contentType:'application/pdf',sizeBytes:10,sha256Checksum:'abc',status:'TEXT_EXTRACTED',active:true,extractedTextAvailable:true}]);vi.spyOn(profileApi,'extractedText').mockResolvedValue({extractedText:'<img src=x onerror=alert(1)>'});render(<ResumeDocumentsPage/>);fireEvent.click(await screen.findByRole('button',{name:'Preview text'}));expect(await screen.findByText('<img src=x onerror=alert(1)>')).toBeInTheDocument();expect(document.querySelector('img')).toBeNull()})
 it('publishes and lists immutable versions',async()=>{vi.spyOn(profileApi,'versions').mockResolvedValue([{id:'v',versionNumber:1,snapshot:{profile:{fullName:'Fictional Candidate'}},checksum:'abc',changeReason:'Initial fictional profile',active:true,createdAt:'2026-01-01',unchanged:false}]);const publish=vi.spyOn(profileApi,'publish').mockResolvedValue({id:'v',versionNumber:1,snapshot:{},checksum:'abc',changeReason:'Ready',active:true,createdAt:'2026-01-01',unchanged:true});render(<ProfileVersionsPage/>);expect(await screen.findByText('Version 1')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Change reason'),{target:{value:'Ready'}});fireEvent.click(screen.getByRole('button',{name:'Publish profile'}));expect(await screen.findByText(/content is unchanged/i)).toBeInTheDocument();expect(publish).toHaveBeenCalledWith('Ready')})
 it('shows field-specific publication validation errors',async()=>{vi.spyOn(profileApi,'versions').mockResolvedValue([]);vi.spyOn(profileApi,'publish').mockRejectedValue({isAxiosError:true,response:{status:422,data:{fieldErrors:{resumeFacts:'Verify at least one resume fact',searchPreferences:'Save search preferences'}}}});render(<ProfileVersionsPage/>);await screen.findByText('No published versions yet.');fireEvent.change(screen.getByLabelText('Change reason'),{target:{value:'Validate fictional profile'}});fireEvent.click(screen.getByRole('button',{name:'Publish profile'}));expect(await screen.findByText(/Verify at least one resume fact/)).toBeInTheDocument();expect(screen.getByText(/Save search preferences/)).toBeInTheDocument()})
})
