package com.amit.jobagent.profile.version;
import com.amit.jobagent.audit.*;
import com.amit.jobagent.common.error.*;
import com.amit.jobagent.document.ActiveResumeDocumentProvider;
import com.amit.jobagent.document.ResumeDocumentResponse;
import com.amit.jobagent.preference.ActivePreferenceProvider;
import com.amit.jobagent.preference.SearchPreferenceResponse;
import com.amit.jobagent.profile.*;
import com.amit.jobagent.profile.answer.*;
import com.amit.jobagent.resumefact.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service
public class ProfileSnapshotService {
 private final CandidateProfileVersionRepository repository;private final ActiveProfileProvider profiles;private final ActivePreferenceProvider preferences;private final VerifiedFactProvider facts;private final VerifiedAnswerProvider answers;private final ActiveResumeDocumentProvider documents;private final ResumeEvidenceExtractor resumeEvidenceExtractor;private final AuditService audit;private final ObjectMapper mapper;
 public ProfileSnapshotService(CandidateProfileVersionRepository repository,ActiveProfileProvider profiles,ActivePreferenceProvider preferences,VerifiedFactProvider facts,VerifiedAnswerProvider answers,ActiveResumeDocumentProvider documents,ResumeEvidenceExtractor resumeEvidenceExtractor,AuditService audit,ObjectMapper mapper){this.repository=repository;this.profiles=profiles;this.preferences=preferences;this.facts=facts;this.answers=answers;this.documents=documents;this.resumeEvidenceExtractor=resumeEvidenceExtractor;this.audit=audit;this.mapper=mapper.copy().configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY,true).configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS,true);}
 @Transactional public CandidateProfileVersionResponse publish(PublishProfileRequest request){return snapshot(request.changeReason().trim(),false);}
 /** Refreshes the immutable source automatically whenever the user evaluates a job. */
 @Transactional public CandidateProfileVersionResponse publishAutomatically(){return snapshot("Automatic snapshot from active resume",true);}
 private CandidateProfileVersionResponse snapshot(String reason,boolean includeResumeEvidence){var profile=publishableProfile();var preference=publishablePreferences();var activeDocument=documents.activeMasterResume();var resumeEvidence=documents.activeResumeEvidence();var verifiedFacts=includeResumeEvidence?resumeEvidence.map(r->resumeEvidenceExtractor.extract(profile.id(),r)).orElseGet(List::of):facts.verifiedFacts();var verifiedAnswers=answers.verifiedAnswers();validate(profile,preference,verifiedFacts,activeDocument,!includeResumeEvidence||resumeEvidence.isPresent());var content=new SnapshotContent(profile,preference,verifiedFacts,verifiedAnswers,activeDocument.orElse(null));var json=write(content);var checksum=checksum(json);var latest=repository.findFirstByProfileIdOrderByVersionNumberDesc(profile.id());if(latest.isPresent()&&latest.get().checksum().equals(checksum)){if(!latest.get().active()){repository.findByProfileIdAndActiveTrue(profile.id()).ifPresent(version->{version.deactivate();repository.saveAndFlush(version);});latest.get().activate();repository.saveAndFlush(latest.get());}return map(latest.get(),true);}repository.findByProfileIdAndActiveTrue(profile.id()).ifPresent(version->{version.deactivate();repository.saveAndFlush(version);});var version=new CandidateProfileVersion(profile.id(),latest.map(v->v.versionNumber()+1).orElse(1),json,checksum,reason);var saved=repository.saveAndFlush(version);audit.record(AuditEventType.PROFILE_VERSION_PUBLISHED,"CandidateProfileVersion",saved.id(),"{\"version\":"+saved.versionNumber()+",\"automatic\":"+includeResumeEvidence+"}");return map(saved,false);}
 @Transactional(readOnly=true)public List<CandidateProfileVersionResponse>list(){var id=profiles.requireProfileId();return repository.findByProfileIdOrderByVersionNumberDesc(id).stream().map(v->map(v,false)).toList();}
 @Transactional(readOnly=true)public CandidateProfileVersionResponse get(int number){var id=profiles.requireProfileId();return map(repository.findByProfileIdAndVersionNumber(id,number).orElseThrow(()->new ResourceNotFoundException("Published profile version was not found")),false);}
 @Transactional(readOnly=true)public CandidateProfileVersionResponse active(){var id=profiles.requireProfileId();return map(repository.findByProfileIdAndActiveTrue(id).orElseThrow(()->new ResourceNotFoundException("No active published profile version exists")),false);}
 private static void validate(CandidateProfileResponse p,SearchPreferenceResponse pref,List<ResumeFactResponse> facts,Optional<ResumeDocumentResponse> doc,boolean extracted){var errors=new LinkedHashMap<String,String>();if(p.fullName().isBlank()||p.email().isBlank()||p.professionalTitle().isBlank())errors.put("profile","Core profile is incomplete");if(pref.targetTitles().isEmpty())errors.put("targetTitles","At least one target title is required");if(pref.preferredLocations().isEmpty()&&!pref.remoteAllowed())errors.put("preferredLocations","A preferred location or remote work is required");if(doc.isEmpty())errors.put("masterResume","An active master resume is required");else if(!extracted)errors.put("masterResume","The active resume has no extracted text; upload a text-based PDF or DOCX");if(facts.isEmpty())errors.put("resumeFacts","No usable evidence could be extracted from the active resume");if(!errors.isEmpty())throw new PublishValidationException("Candidate data is not ready for automatic snapshot",errors);}
 private CandidateProfileResponse publishableProfile(){try{return profiles.requireProfile();}catch(ResourceNotFoundException e){throw new PublishValidationException("Candidate data is not ready for publication",Map.of("profile","Core profile has not been configured"));}}
 private SearchPreferenceResponse publishablePreferences(){try{return preferences.requirePreferences();}catch(ResourceNotFoundException e){throw new PublishValidationException("Candidate data is not ready for publication",Map.of("preferences","Search preferences have not been configured"));}}
 private String write(Object value){try{return mapper.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalStateException("Could not serialize profile snapshot",e);}}
 private static String checksum(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("SHA-256 is unavailable",e);}}
 private CandidateProfileVersionResponse map(CandidateProfileVersion v,boolean unchanged){try{return new CandidateProfileVersionResponse(v.id(),v.versionNumber(),mapper.readTree(v.snapshotJson()),v.checksum(),v.changeReason(),v.active(),v.createdAt(),unchanged);}catch(JsonProcessingException e){throw new IllegalStateException("Stored snapshot is invalid",e);}}
 record SnapshotContent(CandidateProfileResponse profile,SearchPreferenceResponse preferences,List<ResumeFactResponse> verifiedResumeFacts,List<ReusableAnswerResponse> verifiedReusableAnswers,ResumeDocumentResponse activeMasterResume){}
}
