package com.amit.jobagent.application.render;

import java.util.List;
import java.util.Objects;

/** Contact values injected by the server rather than generated by an LLM. */
public record ResumeContact(
        String fullName,
        String email,
        String phone,
        String location,
        List<String> profileLinks) {

    public ResumeContact {
        fullName = requireText(fullName, "fullName");
        email = requireText(email, "email");
        phone = optionalText(phone);
        location = optionalText(location);
        profileLinks = nonBlankValues(profileLinks);
    }

    private static String requireText(String value, String field) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(field + " is required");
        }
        return value.trim();
    }

    private static String optionalText(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

    private static List<String> nonBlankValues(List<String> values) {
        if (values == null || values.isEmpty()) {
            return List.of();
        }
        return values.stream()
                .map(value -> Objects.requireNonNull(value, "profileLinks must not contain null"))
                .map(String::trim)
                .filter(value -> !value.isEmpty())
                .toList();
    }
}
