package com.amit.jobagent.application;
import com.amit.jobagent.job.JobMatchingProvider;import com.amit.jobagent.matching.CompletedEvaluationProvider;import com.amit.jobagent.matching.Recommendation;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.util.*;import org.springframework.stereotype.Component;
@Component class ApplicationPackageMapper{
 private final ApplicationPackageRevisionRepository revisions;private final GeneratedContentRepository contents;private final GeneratedClaimRepository claims;private final GeneratedClaimSourceRepository sources;private final ApplicationQuestionDraftRepository questions;private final DocumentArtifactRepository artifacts;private final JobMatchingProvider jobs;private final CompletedEvaluationProvider evaluations;private final ObjectMapper mapper;
 ApplicationPackageMapper(ApplicationPackageRevisionRepository r,GeneratedContentRepository c,GeneratedClaimRepository g,GeneratedClaimSourceRepository s,ApplicationQuestionDraftRepository q,DocumentArtifactRepository a,JobMatchingProvider j,CompletedEvaluationProvider e,ObjectMapper m){revisions=r;contents=c;claims=g;sources=s;questions=q;artifacts=a;jobs=j;evaluations=e;mapper=m;}
 PackageSummaryResponse summary(ApplicationPackage p){var job=jobs.require(p.jobId);ApplicationPackageRevision rev=p.currentRevisionId==null?null:revisions.findById(p.currentRevisionId).orElse(null);var types=rev==null?List.<ArtifactType>of():artifacts.findByRevisionId(rev.id).stream().map(a->a.type).toList();var recommendation=recommendation(rev,p.jobId);return new PackageSummaryResponse(p.getId(),p.jobId,job.title(),job.company(),recommendation,p.status,rev==null?null:rev.revisionNumber,p.getCreatedAt(),p.getUpdatedAt(),p.status==ApplicationPackageStatus.STALE,types);}
 PackageDetailResponse detail(ApplicationPackage p){var entity=p.currentRevisionId==null?null:revisions.findById(p.currentRevisionId).orElse(null);return detail(p,entity);}
 PackageDetailResponse detail(ApplicationPackage p,ApplicationPackageRevision entity){var job=jobs.require(p.jobId);var rev=entity==null?null:revision(entity);return new PackageDetailResponse(p.getId(),p.jobId,job.title(),job.company(),recommendation(entity,p.jobId),p.status,p.createdBy,p.staleReason,p.getRecordVersion(),p.getCreatedAt(),p.getUpdatedAt(),rev);}
 RevisionResponse revision(ApplicationPackageRevision r){var cs=contents.findByRevisionIdOrderByOrderAscIdAsc(r.id);var ids=cs.stream().map(GeneratedContent::getId).toList();var gs=ids.isEmpty()?List.<GeneratedClaim>of():claims.findByContentIdIn(ids);var gIds=gs.stream().map(g->g.id).toList();var sourceList=gIds.isEmpty()?List.<GeneratedClaimSource>of():sources.findByClaimIdIn(gIds);var srcByClaim=new HashMap<UUID,List<GeneratedClaimSource>>();sourceList.forEach(s->srcByClaim.computeIfAbsent(s.claimId,k->new ArrayList<>()).add(s));return new RevisionResponse(r.id,r.packageId,r.revisionNumber,r.profileVersionId,r.evaluationId,r.status,r.reviewStatus,r.reviewRecordVersion,r.jobChecksum,r.profileChecksum,r.evaluationChecksum,r.promptVersion,r.schemaVersion,r.templateVersion,r.model,r.failureCode,r.failureMessage,r.createdAt,r.completedAt,codes(r.warnings),codes(r.unsupportedRequirements),cs.stream().map(this::content).toList(),gs.stream().map(g->{var src=srcByClaim.getOrDefault(g.id,List.of());return new ClaimResponse(g.id,g.contentId,g.text,g.type,g.path,g.validation,codes(g.codes),src.stream().map(s->s.factId).filter(Objects::nonNull).toList(),src.stream().map(s->s.requirementId).filter(Objects::nonNull).toList(),src.stream().map(s->s.jobField).filter(Objects::nonNull).findFirst().orElse(null));}).toList(),questions.findByRevisionIdOrderByCreatedAtAscIdAsc(r.id).stream().map(q->new QuestionDraftResponse(q.id,q.question,q.classification,q.answer,q.answerStatus,q.confidence)).toList(),artifacts.findByRevisionId(r.id).stream().map(a->new ArtifactResponse(a.id,a.type,a.fileName,a.contentType,a.size,a.checksum,a.templateVersion,a.createdAt)).toList());}
 GeneratedContentResponse content(GeneratedContent c){return new GeneratedContentResponse(c.getId(),c.type,c.key,c.order,c.text,c.origin,c.verification,c.userEdited,c.getRecordVersion(),c.getCreatedAt(),c.getUpdatedAt());}private Recommendation recommendation(ApplicationPackageRevision revision,UUID jobId){if(revision==null)return null;try{return evaluations.require(revision.evaluationId,jobId).recommendation();}catch(RuntimeException unavailable){return null;}}private List<String>codes(String json){try{return mapper.readValue(json,new TypeReference<>(){});}catch(Exception e){return List.of("STORED_VALIDATION_CODES_INVALID");}}
}
