package com.amit.jobagent.application;
import java.util.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;import org.springframework.context.annotation.Profile;import org.springframework.stereotype.Component;
@Component @Profile({"local","test"}) @ConditionalOnExpression("'${job-agent.content-generation.enabled:false}' == 'false'")
class DeterministicApplicationContentGenerator implements ApplicationContentGenerator{
 public TailoringPlan plan(ApplicationContentGenerationRequest r){var selected=r.facts().stream().limit(12).map(VerifiedFactSnapshot::id).toList();var skills=r.facts().stream().flatMap(f->f.skillTags().stream()).map(String::trim).filter(s->!s.isEmpty()).distinct().limit(30).toList();return new TailoringPlan(selected,List.of(),skills,r.jobRequirements().stream().map(JobRequirementSnapshot::text).toList(),List.of(),"concise-professional");}
 public GeneratedApplicationContent generate(ApplicationContentGenerationRequest r,TailoringPlan p){var byId=new LinkedHashMap<UUID,VerifiedFactSnapshot>();r.facts().forEach(f->byId.put(f.id(),f));var contents=new ArrayList<GeneratedContentItem>();var claims=new ArrayList<GeneratedClaimAtom>();int order=0;var selected=p.selectedFactIds().stream().map(byId::get).filter(Objects::nonNull).toList();if(!selected.isEmpty()){var first=selected.getFirst();contents.add(new GeneratedContentItem(GeneratedContentType.RESUME_HEADLINE,"headline",order++,first.statement()));claims.add(new GeneratedClaimAtom("headline",first.statement(),ClaimType.CANDIDATE_FACT,List.of(first.id()),List.of(),null));String summary=selected.stream().limit(2).map(VerifiedFactSnapshot::statement).reduce((a,b)->a+" "+b).orElse(first.statement());contents.add(new GeneratedContentItem(GeneratedContentType.PROFESSIONAL_SUMMARY,"summary",order++,summary));for(var f:selected.stream().limit(2).toList())claims.add(new GeneratedClaimAtom("summary",f.statement(),ClaimType.CANDIDATE_FACT,List.of(f.id()),List.of(),null));}
 if(!p.orderedSkills().isEmpty()){String skills=String.join(", ",p.orderedSkills());contents.add(new GeneratedContentItem(GeneratedContentType.SKILL_SECTION,"skills",order++,skills));var support=r.facts().stream().filter(f->f.skillTags().stream().anyMatch(p.orderedSkills()::contains)).map(VerifiedFactSnapshot::id).toList();claims.add(new GeneratedClaimAtom("skills",skills,ClaimType.CANDIDATE_FACT,support,List.of(),null));}
 for(var f:selected){var type="PROJECT".equals(f.category())?GeneratedContentType.PROJECT_BULLET:"EDUCATION".equals(f.category())?GeneratedContentType.EDUCATION_SECTION:GeneratedContentType.EXPERIENCE_BULLET;String key="fact-"+f.id();contents.add(new GeneratedContentItem(type,key,order++,f.statement()));claims.add(new GeneratedClaimAtom(key,f.statement(),ClaimType.CANDIDATE_FACT,List.of(f.id()),List.of(),null));}
 String intro="I am excited to apply for the "+r.jobTitle()+" role at "+r.company()+".";contents.add(new GeneratedContentItem(GeneratedContentType.COVER_LETTER,"cover-letter",order++,intro+(selected.isEmpty()?"":" "+selected.getFirst().statement())));claims.add(new GeneratedClaimAtom("cover-letter",intro,ClaimType.JOB_REFERENCE,List.of(),List.of(),"job.title,job.company"));if(!selected.isEmpty())claims.add(new GeneratedClaimAtom("cover-letter",selected.getFirst().statement(),ClaimType.CANDIDATE_FACT,List.of(selected.getFirst().id()),List.of(),null));String message="Hello, I am interested in the "+r.jobTitle()+" role at "+r.company()+".";contents.add(new GeneratedContentItem(GeneratedContentType.RECRUITER_MESSAGE,"recruiter-message",order,message));claims.add(new GeneratedClaimAtom("recruiter-message",message,ClaimType.JOB_REFERENCE,List.of(),List.of(),"job.title,job.company"));return new GeneratedApplicationContent(List.copyOf(contents),List.copyOf(claims),List.of(),p.unsupportedRequirements());}
}
