package com.amit.jobagent.application;

import com.amit.jobagent.common.error.ResourceNotFoundException;import com.amit.jobagent.document.ObjectStorage;import com.amit.jobagent.job.JobMatchingProvider;import com.amit.jobagent.matching.CompletedEvaluationProvider;import com.amit.jobagent.profile.ActiveProfileProvider;import com.amit.jobagent.profile.version.PublishedProfileProvider;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class HandoffEligibilityService{
 private final ApplicationPackageRepository packages;private final ApplicationPackageRevisionRepository revisions;private final GeneratedContentRepository contents;private final GeneratedClaimRepository claims;private final GeneratedClaimSourceRepository sources;private final ApplicationQuestionDraftRepository questions;private final DocumentArtifactRepository artifacts;private final ApplicationReviewDecisionRepository decisions;private final JobMatchingProvider jobs;private final CompletedEvaluationProvider evaluations;private final PublishedProfileProvider profiles;private final ActiveProfileProvider activeProfiles;private final ObjectStorage storage;
 public HandoffEligibilityService(ApplicationPackageRepository p,ApplicationPackageRevisionRepository r,GeneratedContentRepository c,GeneratedClaimRepository g,GeneratedClaimSourceRepository s,ApplicationQuestionDraftRepository q,DocumentArtifactRepository a,ApplicationReviewDecisionRepository d,JobMatchingProvider j,CompletedEvaluationProvider e,PublishedProfileProvider pv,ActiveProfileProvider ap,ObjectStorage os){packages=p;revisions=r;contents=c;claims=g;sources=s;questions=q;artifacts=a;decisions=d;jobs=j;evaluations=e;profiles=pv;activeProfiles=ap;storage=os;}
 @Transactional(readOnly=true)public HandoffEligibility check(UUID packageId,UUID revisionId){var p=owned(packageId);var r=revisions.findByPackageIdAndId(packageId,revisionId).orElseThrow(()->new ResourceNotFoundException("Package revision was not found"));var reasons=new ArrayList<BlockingReason>();
  if(r.status!=RevisionStatus.READY)block(reasons,"GENERATION_OR_VALIDATION_NOT_READY","Revision generation and validation must be successful");if(p.currentRevisionId==null||!p.currentRevisionId.equals(r.id)||p.status!=ApplicationPackageStatus.READY)block(reasons,"REVISION_STALE","Only the current, non-stale revision can be handed off");
  try{if(!Objects.equals(jobs.require(p.jobId).contentHash(),r.jobChecksum))block(reasons,"SOURCE_JOB_CHANGED","The source job checksum changed");}catch(RuntimeException x){block(reasons,"SOURCE_JOB_UNAVAILABLE","The source job is unavailable");}
  try{var profile=profiles.require(r.profileVersionId);if(!Objects.equals(profile.checksum(),r.profileChecksum)||!Objects.equals(profiles.requireActive().id(),r.profileVersionId))block(reasons,"SOURCE_PROFILE_CHANGED","The active profile or its checksum changed");}catch(RuntimeException x){block(reasons,"SOURCE_PROFILE_UNAVAILABLE","The source profile is unavailable");}
  try{var evaluation=evaluations.require(r.evaluationId,p.jobId);if(evaluation.stale()||!Objects.equals(evaluation.checksum(),r.evaluationChecksum))block(reasons,"SOURCE_EVALUATION_CHANGED","The evaluation is stale or its checksum changed");}catch(RuntimeException x){block(reasons,"SOURCE_EVALUATION_UNAVAILABLE","The source evaluation is unavailable");}
  var cs=contents.findByRevisionIdOrderByOrderAscIdAsc(r.id);var gs=cs.isEmpty()?List.<GeneratedClaim>of():claims.findByContentIdIn(cs.stream().map(GeneratedContent::getId).toList());var src=gs.isEmpty()?List.<GeneratedClaimSource>of():sources.findByClaimIdIn(gs.stream().map(x->x.id).toList());var sourced=src.stream().filter(x->x.candidateEvidenceId()!=null).map(x->x.claimId).collect(java.util.stream.Collectors.toSet());if(gs.stream().anyMatch(x->x.validation!=ClaimValidationStatus.VALID||(x.type==ClaimType.CANDIDATE_FACT&&!sourced.contains(x.id))))block(reasons,"INVALID_CLAIM_PROVENANCE","Every candidate claim must have valid fact evidence");
  var qs=questions.findByRevisionIdOrderByCreatedAtAscIdAsc(r.id);if(qs.stream().anyMatch(x->x.classification==QuestionClassification.SENSITIVE_NEVER_AUTOMATIC&&x.answer!=null))block(reasons,"SENSITIVE_QUESTION_AUTO_ANSWERED","Sensitive questions must remain unanswered automatically");
  String manifest=artifactManifest(r.id,reasons);String validation=validationChecksum(gs,qs,r);var approved=decisions.findByRevisionIdOrderByCreatedAtDesc(r.id).stream().filter(x->x.decision==ReviewDecisionType.APPROVED_FOR_HANDOFF&&x.invalidatedAt==null).findFirst().orElse(null);if(r.reviewStatus!=ReviewStatus.APPROVED_FOR_HANDOFF||approved==null)block(reasons,"REVISION_NOT_APPROVED","An active approval for this exact revision is required");else{if(!Objects.equals(approved.artifactChecksum,manifest))block(reasons,"APPROVED_ARTIFACTS_CHANGED","Artifact manifest no longer matches the approval");if(!Objects.equals(approved.validationChecksum,validation))block(reasons,"APPROVED_VALIDATION_CHANGED","Validation state no longer matches the approval");}
  return new HandoffEligibility(packageId,revisionId,reasons.isEmpty(),r.reviewStatus,r.reviewRecordVersion,List.copyOf(reasons),manifest,validation);}
 String artifactManifest(UUID revisionId,List<BlockingReason>reasons){var list=new ArrayList<>(artifacts.findByRevisionId(revisionId));list.sort(Comparator.comparing(x->x.type.name()));for(var type:ArtifactType.values())if(list.stream().noneMatch(x->x.type==type))block(reasons,"REQUIRED_ARTIFACT_MISSING","Required artifact is missing: "+type);for(var a:list)try{byte[] b=storage.load(a.storageKey);if(b.length!=a.size||!hash(b).equals(a.checksum))block(reasons,"ARTIFACT_INTEGRITY_FAILED","Artifact is missing or corrupt: "+a.type);}catch(RuntimeException x){block(reasons,"ARTIFACT_UNREADABLE","Artifact cannot be read: "+a.type);}return hash(list.stream().map(x->x.type+":"+x.checksum+":"+x.size).reduce("",(a,b)->a+"|"+b));}
 String validationChecksum(List<GeneratedClaim>gs,List<ApplicationQuestionDraft>qs,ApplicationPackageRevision r){String claimsPart=gs.stream().sorted(Comparator.comparing(x->x.id)).map(x->x.id+":"+x.validation+":"+x.codes).reduce("",(a,b)->a+"|"+b);String questionsPart=qs.stream().sorted(Comparator.comparing(x->x.id)).map(x->x.id+":"+x.classification+":"+x.answerStatus+":"+(x.answer==null)).reduce("",(a,b)->a+"|"+b);return hash(r.status+claimsPart+questionsPart);}
 ApplicationPackage owned(UUID id){UUID candidate=activeProfiles.requireProfileId();return packages.findById(id).filter(x->x.candidateId.equals(candidate)).orElseThrow(()->new ResourceNotFoundException("Application package was not found"));}static void block(List<BlockingReason>x,String code,String message){if(x.stream().noneMatch(b->b.code().equals(code)))x.add(new BlockingReason(code,message));}static String hash(byte[]v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v));}catch(Exception e){throw new IllegalStateException(e);}}static String hash(String v){return hash(v.getBytes(StandardCharsets.UTF_8));}
}
